@host = localhost:4000
// Create Consultation
POST http://{{host}}/api/consultations HTTP/1.1
content-type: application/json

{
    "Name": "Test5",
    "Year": "2001",
    "Hospital": "Test",
    "Pharmacist": "test",
    "Medication": "Test",
    "Quantity": "10"
}
###
// Get Consultation By ID
GET http://{{host}}/api/consultations/1 HTTP/1.1
content-type: application/json
###
// Get All Consultations
GET http://{{host}}/api/consultations/ HTTP/1.1
content-type: application/json
###
// Get Status
GET http://{{host}}/api/status/ HTTP/1.1
content-type: application/json
###
// Update Consultation
PUT http://{{host}}/api/consultations/1 HTTP/1.1
content-type: application/json
{
    "Name": "Test",
    "Year": "2001",
    "Hospital": "Test",
    "Pharmacist": "test",
    "Medication": "Test",
    "Quantity": "10"
}
###